rest_server_port: 30099
output_folder: /outputs/
newman_folder: /app/resources/newman/
api_monitor: /app/monitors/api/
rest_controllers: /app/controllers/
test_data: /test/app/resources/data/
test_file: tests.json
env_file: env.json
global_file: globals.json
report_file_end: -report.json
env_export_file_end: -env.json
verbose_file_end: -debug
full_report_file_end: -full-report.json
monitor_schedule:
  default: "* * * * *"
slack_api: https://slack.com/api/
slack_token: xoxb-40319046768-RsDQAkXW989SZmBfoXAVk3R2
slack_message_options:
  channel:  "#identity-site-alerts"
  icon_emoji: ":loudspeaker:"
  pretty: 1
  link_names: 1
slack_upload_options:
  channels:  "#identity-alarms"
  fileType: log
disable_slack_notifications: false
disable_metrics: false
disable_info_notices: true
metrics_prefix: test.
metrics_default_name: monitor
aws_s3_bucket: monitoring-debug-data
aws_s3_file_expiration_days: 30
