rest_server_port: 30099
output_folder: /outputs/
newman_folder: /app/resources/newman/
api_monitor: /app/monitor/
rest_controllers: /app/controllers/
test_data: /test/app/resources/data/
test_file: tests.json
env_file: env.json
global_file: globals.json
report_file_end: -report.json
monitor_schedule:
  default: "*/5 * * * *"
metrics_prefix: test.
metrics_agent_host: localhost
metrics_agent_port: 8125
metrics_default_api_name: api.monitor
metrics_disabled: 0
datadog_failure_notification_disabled: 0
aws_s3_bucket: monitoring-debug-data
aws_s3_file_expiration_days: 30
aws_s3_disable_push: 1
log_level: info
