supported_monitors: [ brandapi-user, brandapi-support, brandapi-migration]
mongo_db: mongodb://localhost:27017/apimonitor
rest_server_port: 30099
slack_upload_options:
  channels:  "#identity-site-alerts"